FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY [".", "./"]
RUN dotnet restore "./TMDT.csproj"
COPY . .
WORKDIR "/src/TMDT"
RUN dotnet build "TMDT.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TMDT.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TMDT.dll"]
